export { HowThisWorks } from '@/components/Main/HowThisWorks'
export { WhoCanParticipate } from '@/components/Main/WhoCanParticipate'
export { AboutService } from '@/components/Main/AboutService'
export { QNA } from '@/components/Main/QNA'
export { Feedback } from '@/components/Main/Feedback'
