import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { Constants } from '@/types'
import { ToastContainer } from 'react-toastify'
import '@/assets/index.scss'
import 'react-toastify/dist/ReactToastify.css'

const manrope = Manrope({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
	title: Constants.PROJECT_NAME,
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<ToastContainer />
				{children}
			</body>
		</html>
	)
}
