import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Constants } from '@/types';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: Constants.PROJECT_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
